### ISSUE TITLE
eslint-plugin-typescript is deprecated.

### ISSUE THREAD

**Issue by ilhan-mstf** [EmakinaTR/makina-api#35]
https://github.com/bradzacher/eslint-plugin-typescript/issues/290
I've some eslint related issues while integrating type-graphql library. I've searched for solutions to overcome these issues, and now, I've realized that eslint plugin was deprecated a few days ago. We need to move newer package.

**Comment by koraytaylan** [comment]
Looks a bit early to switch. There is no documentation for how to configure it yet 🤔
