### ISSUE TITLE
Create Dockerfile for Redis

### ISSUE THREAD

**Issue by ugurcemozturk** [EmakinaTR/makina-api#4]
- [ ] Use the latest production-ready docker image

- If a clustered redis needed:

   - [ ] consider using redis-sentinel

   - [ ] If a clustered redis needed, create a docker compose file

**Comment by koraytaylan** [comment]
Let's follow this up on #15 since it has a broader scope. Btw I think we should consider redis after we have a semi-stable api where we can assess our caching needs better. Premature optimization is the root of all the evil after all. 😄
